name: MidoriLobbyTeleport
version: 1.1
main: midorichan.LobbyTeleport
api-version: 1.18
author: midorichan
website: https://twitter.com/Midorichaan2525

commands:
  lobby:
    description: jump to lobby
    default: true
    aliases: [c]
  mrl:
    description: reload config
    default: op

permissions:
  midorilobby.use:
    default: true
  midorilobby.use.admin:
    default: op
  midorilobby.reload:
    default: op